version: "2"

checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: false
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 50
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.

plugins:
  eslint:
    enabled: true
    channel: "eslint-6"
    exclude_patterns:
      - "app/javascript/**/index.js" # exclude barrel files
  duplication:
    enabled: true
    config:
      count_threshold: 3

engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      ignore_warnings: true
      config: .eslintrc.json
  csslint:
    enabled: false
  stylelint:
    enabled: false
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - typescript
        - javascript:
            mass_threshold: 75

ratings:
  paths:
  - "**.css"
  - "**.ts"

exclude_patterns:
  - "**/*.test.js"
  - "**/.eslintrc.js"
  - "**/__stories__/"
  - "**/__tests__/"
  - "*.js"
  - "bin/"
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "lib/tasks/"
  - "node_modules/"
  - "script/"
  - "spec/"
  - "test/"
  - "tests/"
  - "vendor/"
