curators:
  - alexrogalskiy

features:
  - dco_check
  - comments
  - pr_description_required
  - release_notes
  - hacktoberfest

contributing_url: https://github.com/AlexRogalskiy/github-action-user-contribution/blob/master/.github/CONTRIBUTING.md
