---
APPLY_FIXES: none
DISABLE:
  - ACTION
  - BASH
  - COPYPASTE
  - DOCKERFILE
  - GO
  - JAVASCRIPT
  - SPELL
DISABLE_LINTERS:
  - YAML_YAMLLINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - MARKDOWN_MARKDOWN_LINK_CHECK
FILTER_REGEX_EXCLUDE: (.*testdata/*|install.sh)
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yml
PARALLEL: false
PRINT_ALPACA: false
