pull_request_rules:
  - name: automatic merge on CI success require review
    conditions:
      - status-success=Travis CI - Pull Request
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=block-merge
    actions:
      label:
        add:
          - github-actions
      merge:
        method: squash
        strict: smart
        strict_method: merge

  # if there is a conflict in a backport PR, ping the author to send a proper backport PR
  - name: ping author on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request has merge conflicts that must be resolved before it can be merged. @{{author}} please rebase it. https://rook.io/docs/rook/master/development-flow.html#updating-your-fork

  # automerge on master only under certain strict conditions
  - name: automerge merge master with specific label and approvals with code change
    conditions:
      - author=mergify[bot]
      - base=master
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
      - label=ready-to-merge
    actions:
      merge:
        method: merge
        strict: false
      dismiss_reviews: { }
      delete_head_branch: { }

  - name: automatic merge on CI success for TemplateControl
    conditions:
      - status-success=Travis CI - Pull Request
      - label=merge-when-green
      - label!=block-merge
    actions:
      merge:
        method: squash
        strict: smart

  - name: delete branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: { }

  - name: Automatically approve Dependabot PRs
    conditions:
      - base=master
      - author~=^dependabot(|-preview)\[bot\]$
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
    actions:
      review:
        type: APPROVE

  - name: Automatic maintainer assignment
    conditions:
      - "-approved-reviews-by=@nektos/act-maintainers"
      - -draft
      - -merged
      - -closed
      - -conflict
      - check-success=lint
      - check-success=test-linux
      - check-success=test-macos
      - check-success=codecov/patch
      - check-success=codecov/project
      - check-success=snapshot
    actions:
      request_reviews:
        teams:
          - "@nektos/act-maintainers"

  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
      label:
        add:
          - conflict

  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict

  - name: warn on needs-work
    conditions:
      - "#check-failure>=1"
    actions:
      comment:
        message: "@{{author}} this pull request has failed checks 🛠"
      label:
        add:
          - needs-work
  - name: remove needs-work label if not needed
    conditions:
      - check-success=lint
      - check-success=test-linux
      - check-success=test-macos
      - check-success=codecov/patch
      - check-success=codecov/project
      - check-success=snapshot
    actions:
      label:
        remove:
          - needs-work

  - name: Automatic committer assignment
    conditions:
      - "approved-reviews-by=@nektos/act-maintainers"
      - "-approved-reviews-by=@nektos/act-committers"
      - -draft
      - -merged
      - -closed
      - -conflict
      - check-success=lint
      - check-success=test-linux
      - check-success=test-macos
      - check-success=codecov/patch
      - check-success=codecov/project
      - check-success=snapshot
    actions:
      request_reviews:
        teams:
          - "@nektos/act-committers"

  - name: Automatic merge on approval
    conditions:
      - "#changes-requested-reviews-by=0"
      - "approved-reviews-by=@nektos/act-committers"
      - -draft
      - -merged
      - -closed
      - check-success=lint
      - check-success=test-linux
      - check-success=test-macos
      - check-success=codecov/patch
      - check-success=codecov/project
      - check-success=snapshot
    actions:
      merge:
        method: squash
        strict: true
