name: markdown-autodocs

on:
  workflow_run:
    workflows:
      - generate-artifacts
    types:
      - completed

jobs:
  auto-update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.3
